// Code generated by protoc-gen-go. DO NOT EDIT.
// source: numbers-storage.proto

package main

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SetNumbersRequest struct {
	X                    int64    `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int64    `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetNumbersRequest) Reset()         { *m = SetNumbersRequest{} }
func (m *SetNumbersRequest) String() string { return proto.CompactTextString(m) }
func (*SetNumbersRequest) ProtoMessage()    {}
func (*SetNumbersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_21a9708ad786ff23, []int{0}
}

func (m *SetNumbersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetNumbersRequest.Unmarshal(m, b)
}
func (m *SetNumbersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetNumbersRequest.Marshal(b, m, deterministic)
}
func (m *SetNumbersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetNumbersRequest.Merge(m, src)
}
func (m *SetNumbersRequest) XXX_Size() int {
	return xxx_messageInfo_SetNumbersRequest.Size(m)
}
func (m *SetNumbersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetNumbersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetNumbersRequest proto.InternalMessageInfo

func (m *SetNumbersRequest) GetX() int64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *SetNumbersRequest) GetY() int64 {
	if m != nil {
		return m.Y
	}
	return 0
}

type SetNumbersResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetNumbersResponse) Reset()         { *m = SetNumbersResponse{} }
func (m *SetNumbersResponse) String() string { return proto.CompactTextString(m) }
func (*SetNumbersResponse) ProtoMessage()    {}
func (*SetNumbersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_21a9708ad786ff23, []int{1}
}

func (m *SetNumbersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetNumbersResponse.Unmarshal(m, b)
}
func (m *SetNumbersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetNumbersResponse.Marshal(b, m, deterministic)
}
func (m *SetNumbersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetNumbersResponse.Merge(m, src)
}
func (m *SetNumbersResponse) XXX_Size() int {
	return xxx_messageInfo_SetNumbersResponse.Size(m)
}
func (m *SetNumbersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetNumbersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetNumbersResponse proto.InternalMessageInfo

type GetNumbersRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNumbersRequest) Reset()         { *m = GetNumbersRequest{} }
func (m *GetNumbersRequest) String() string { return proto.CompactTextString(m) }
func (*GetNumbersRequest) ProtoMessage()    {}
func (*GetNumbersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_21a9708ad786ff23, []int{2}
}

func (m *GetNumbersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNumbersRequest.Unmarshal(m, b)
}
func (m *GetNumbersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNumbersRequest.Marshal(b, m, deterministic)
}
func (m *GetNumbersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNumbersRequest.Merge(m, src)
}
func (m *GetNumbersRequest) XXX_Size() int {
	return xxx_messageInfo_GetNumbersRequest.Size(m)
}
func (m *GetNumbersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNumbersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetNumbersRequest proto.InternalMessageInfo

type GetNumbersResponse struct {
	X                    int64    `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int64    `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNumbersResponse) Reset()         { *m = GetNumbersResponse{} }
func (m *GetNumbersResponse) String() string { return proto.CompactTextString(m) }
func (*GetNumbersResponse) ProtoMessage()    {}
func (*GetNumbersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_21a9708ad786ff23, []int{3}
}

func (m *GetNumbersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNumbersResponse.Unmarshal(m, b)
}
func (m *GetNumbersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNumbersResponse.Marshal(b, m, deterministic)
}
func (m *GetNumbersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNumbersResponse.Merge(m, src)
}
func (m *GetNumbersResponse) XXX_Size() int {
	return xxx_messageInfo_GetNumbersResponse.Size(m)
}
func (m *GetNumbersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNumbersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetNumbersResponse proto.InternalMessageInfo

func (m *GetNumbersResponse) GetX() int64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *GetNumbersResponse) GetY() int64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func init() {
	proto.RegisterType((*SetNumbersRequest)(nil), "main.SetNumbersRequest")
	proto.RegisterType((*SetNumbersResponse)(nil), "main.SetNumbersResponse")
	proto.RegisterType((*GetNumbersRequest)(nil), "main.GetNumbersRequest")
	proto.RegisterType((*GetNumbersResponse)(nil), "main.GetNumbersResponse")
}

func init() { proto.RegisterFile("numbers-storage.proto", fileDescriptor_21a9708ad786ff23) }

var fileDescriptor_21a9708ad786ff23 = []byte{
	// 170 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcd, 0x2b, 0xcd, 0x4d,
	0x4a, 0x2d, 0x2a, 0xd6, 0x2d, 0x2e, 0xc9, 0x2f, 0x4a, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0x62, 0xc9, 0x4d, 0xcc, 0xcc, 0x53, 0xd2, 0xe7, 0x12, 0x0c, 0x4e, 0x2d, 0xf1, 0x83,
	0xa8, 0x08, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0xe2, 0xe1, 0x62, 0xac, 0x90, 0x60, 0x54,
	0x60, 0xd4, 0x60, 0x0e, 0x62, 0xac, 0x00, 0xf1, 0x2a, 0x25, 0x98, 0x20, 0xbc, 0x4a, 0x25, 0x11,
	0x2e, 0x21, 0x64, 0x0d, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x4a, 0xc2, 0x5c, 0x82, 0xee, 0xe8,
	0xc6, 0x28, 0x19, 0x70, 0x09, 0xb9, 0x63, 0x28, 0xc5, 0x67, 0xb8, 0xd1, 0x34, 0x46, 0x2e, 0x3e,
	0xa8, 0xfa, 0x60, 0x88, 0x63, 0x85, 0x1c, 0xb9, 0xb8, 0x10, 0xf6, 0x09, 0x89, 0xeb, 0x81, 0x5c,
	0xad, 0x87, 0xe1, 0x64, 0x29, 0x09, 0x4c, 0x09, 0xa8, 0xd3, 0x18, 0x40, 0x46, 0xb8, 0x63, 0x18,
	0xe1, 0x8e, 0xcb, 0x08, 0x77, 0x2c, 0x46, 0x24, 0xb1, 0x81, 0xc3, 0xcc, 0x18, 0x10, 0x00, 0x00,
	0xff, 0xff, 0xe5, 0xfb, 0xf4, 0xbe, 0x4c, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NumbersStorageClient is the client API for NumbersStorage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NumbersStorageClient interface {
	SetNumbers(ctx context.Context, in *SetNumbersRequest, opts ...grpc.CallOption) (*SetNumbersResponse, error)
	GetNumbers(ctx context.Context, in *GetNumbersRequest, opts ...grpc.CallOption) (*GetNumbersResponse, error)
}

type numbersStorageClient struct {
	cc *grpc.ClientConn
}

func NewNumbersStorageClient(cc *grpc.ClientConn) NumbersStorageClient {
	return &numbersStorageClient{cc}
}

func (c *numbersStorageClient) SetNumbers(ctx context.Context, in *SetNumbersRequest, opts ...grpc.CallOption) (*SetNumbersResponse, error) {
	out := new(SetNumbersResponse)
	err := c.cc.Invoke(ctx, "/main.NumbersStorage/SetNumbers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *numbersStorageClient) GetNumbers(ctx context.Context, in *GetNumbersRequest, opts ...grpc.CallOption) (*GetNumbersResponse, error) {
	out := new(GetNumbersResponse)
	err := c.cc.Invoke(ctx, "/main.NumbersStorage/GetNumbers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NumbersStorageServer is the server API for NumbersStorage service.
type NumbersStorageServer interface {
	SetNumbers(context.Context, *SetNumbersRequest) (*SetNumbersResponse, error)
	GetNumbers(context.Context, *GetNumbersRequest) (*GetNumbersResponse, error)
}

// UnimplementedNumbersStorageServer can be embedded to have forward compatible implementations.
type UnimplementedNumbersStorageServer struct {
}

func (*UnimplementedNumbersStorageServer) SetNumbers(ctx context.Context, req *SetNumbersRequest) (*SetNumbersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetNumbers not implemented")
}
func (*UnimplementedNumbersStorageServer) GetNumbers(ctx context.Context, req *GetNumbersRequest) (*GetNumbersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNumbers not implemented")
}

func RegisterNumbersStorageServer(s *grpc.Server, srv NumbersStorageServer) {
	s.RegisterService(&_NumbersStorage_serviceDesc, srv)
}

func _NumbersStorage_SetNumbers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetNumbersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NumbersStorageServer).SetNumbers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.NumbersStorage/SetNumbers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NumbersStorageServer).SetNumbers(ctx, req.(*SetNumbersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NumbersStorage_GetNumbers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNumbersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NumbersStorageServer).GetNumbers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.NumbersStorage/GetNumbers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NumbersStorageServer).GetNumbers(ctx, req.(*GetNumbersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _NumbersStorage_serviceDesc = grpc.ServiceDesc{
	ServiceName: "main.NumbersStorage",
	HandlerType: (*NumbersStorageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetNumbers",
			Handler:    _NumbersStorage_SetNumbers_Handler,
		},
		{
			MethodName: "GetNumbers",
			Handler:    _NumbersStorage_GetNumbers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "numbers-storage.proto",
}
